# Alembic Configuration File

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
;file_template = %%(asctime)s_%%(rev)s-%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.datetime.now(datetime.timezone(datetime.timedelta(0)))
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field (template in file_template)
# set to 0 to omit, -1 to indefinitely postpone
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# When set to "true", this option prevents new revision files
# from being written to disk. See the caveats section in the
# Alembic documentation for more information. This option is
# useful as a starting point to use newer Alembic features via
# in-process mechanisms such as Runner.run_migrations_to_sql().
# revision_environment = false


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
